# Generated by Django 2.2.5 on 2020-03-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0019_borne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borne',
        ),
    ]
