# Generated by Django 2.2.5 on 2020-03-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0021_borne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borne',
            name='picture',
            field=models.ImageField(default='C:\\Users\\Arthur Tankwa\\Documents\\tutos\\programmation\\python\\Django\\Geodjango\\agricom\\defaut.jpg', upload_to=''),
        ),
    ]
