# Generated by Django 4.1 on 2023-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0023_alter_borne_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borne',
            name='picture',
            field=models.ImageField(default='C:\\Users\\User\\Documents\\programmation\\python\\Django\\Geodjango\\Geoportail_test\\defaut.jpg', upload_to=''),
        ),
    ]
