# Generated by Django 4.1 on 2023-01-19 10:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0024_alter_borne_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_aot', models.IntegerField()),
                ('amodiatair', models.CharField(max_length=50)),
                ('rccm', models.CharField(max_length=50)),
                ('niu', models.CharField(max_length=50)),
                ('bp', models.CharField(max_length=50)),
                ('tel', models.BigIntegerField()),
                ('duree_bail', models.IntegerField()),
                ('taux_loyer', models.IntegerField()),
                ('sup', models.FloatField()),
                ('mont_cauti', models.BigIntegerField()),
                ('date_caut', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Borne',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
