# Generated by Django 4.1 on 2023-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0025_aot_delete_borne_delete_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
