# Generated by Django 4.1.3 on 2023-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0026_alter_aot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aot',
            name='Remarque',
            field=models.CharField(default='R.A.S.', max_length=50),
        ),
        migrations.AddField(
            model_name='aot',
            name='statut',
            field=models.CharField(choices=[('green', 'Bon'), ('orange', 'Intermédiaire'), ('red', 'Critique')], default='green', max_length=50),
        ),
    ]
