# Generated by Django 4.1.3 on 2023-02-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0029_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='id_index',
        ),
    ]
