# Generated by Django 4.1.3 on 2023-04-13 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0030_remove_index_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
