# Generated by Django 4.1.3 on 2023-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0031_alter_index_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aot',
            name='date_caut',
        ),
        migrations.RemoveField(
            model_name='aot',
            name='mont_cauti',
        ),
        migrations.RemoveField(
            model_name='aot',
            name='sup',
        ),
        migrations.AddField(
            model_name='aot',
            name='date_caution',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='aot',
            name='date_debut',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='aot',
            name='date_fin',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='aot',
            name='montant_caution',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='aot',
            name='superficie',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='aot',
            name='duree_bail',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='aot',
            name='taux_loyer',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='aot',
            name='tel',
            field=models.BigIntegerField(default=None),
        ),
    ]
