# Generated by Django 4.1.3 on 2023-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0032_remove_aot_date_caut_remove_aot_mont_cauti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='join_fid',
        ),
        migrations.AlterField(
            model_name='index',
            name='ancien_ind',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='code_tarif',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='coef',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='compteur',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='conso_m3',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='entretien',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='mont_conso',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='mont_payer',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='nouvel_ind',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='index',
            name='prix_unit',
            field=models.BigIntegerField(default=None),
        ),
    ]
