# Generated by Django 4.1.3 on 2023-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0033_remove_index_join_fid_alter_index_ancien_ind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aot',
            old_name='amodiatair',
            new_name='amodiataire',
        ),
    ]
