# Generated by Django 4.1.3 on 2023-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0034_rename_amodiatair_aot_amodiataire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='amodiatair',
            new_name='amodiataire',
        ),
    ]
