# Generated by Django 4.1.3 on 2023-04-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0036_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='aot',
            name='Localisatio',
            field=models.CharField(choices=[('Zone avale', 'Zone avale'), ('Parc à bois', 'Parc à bois'), ('Zone de pêche', 'Zone de pêche')], default=None, max_length=50, null=True),
        ),
    ]
