# Generated by Django 4.1.3 on 2023-04-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0037_aot_localisatio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aot',
            old_name='Localisatio',
            new_name='Localisation',
        ),
    ]
