# Generated by Django 4.1.3 on 2023-04-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0038_rename_localisatio_aot_localisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aot',
            old_name='Localisation',
            new_name='localisation',
        ),
    ]
