# Generated by Django 4.1.3 on 2024-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0039_rename_localisation_aot_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aot',
            name='remarque',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
