# Generated by Django 4.1.3 on 2024-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0040_alter_aot_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aot',
            name='remarque',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
