# Generated by Django 4.1.3 on 2024-03-01 14:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0041_alter_aot_remarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheminFer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_id', models.CharField(max_length=25)),
                ('usage', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('gauge', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_id', models.CharField(max_length=25)),
                ('highway', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('oneway', models.CharField(max_length=10)),
                ('surface', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
