# Generated by Django 4.1.3 on 2024-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0042_cheminfer_reseauelec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheminfer',
            name='gauge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cheminfer',
            name='service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cheminfer',
            name='usage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='highway',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='oneway',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='surface',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
