# Generated by Django 4.1.3 on 2024-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0043_alter_cheminfer_gauge_alter_cheminfer_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseauelec',
            name='highway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='oneway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reseauelec',
            name='surface',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
