# Generated by Django 4.1.3 on 2024-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0044_alter_reseauelec_highway_alter_reseauelec_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aot',
            name='bp',
            field=models.CharField(max_length=50, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='date_caution',
            field=models.DateField(default=None, verbose_name='Date paiement caution'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='date_debut',
            field=models.DateField(default=None, verbose_name='Date début loyer'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='date_fin',
            field=models.DateField(default=None, verbose_name='Date expiration loyer'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='duree_bail',
            field=models.IntegerField(default=None, verbose_name='Durée Bail'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='montant_caution',
            field=models.BigIntegerField(default=None, verbose_name='Montant caution'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='niu',
            field=models.CharField(max_length=50, verbose_name='NIU'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='rccm',
            field=models.CharField(max_length=50, verbose_name='RCCM'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='superficie',
            field=models.FloatField(default=None, verbose_name='Superficie (m²)'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='taux_loyer',
            field=models.IntegerField(default=None, verbose_name='Taux loyer (CFA/m²)'),
        ),
        migrations.AlterField(
            model_name='aot',
            name='tel',
            field=models.BigIntegerField(default=None, verbose_name='Tel'),
        ),
        migrations.AlterField(
            model_name='index',
            name='ancien_ind',
            field=models.IntegerField(default=None, verbose_name='Ancien index'),
        ),
        migrations.AlterField(
            model_name='index',
            name='bp',
            field=models.CharField(max_length=50, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='index',
            name='mont_conso',
            field=models.BigIntegerField(default=None, verbose_name='Montant consommation'),
        ),
        migrations.AlterField(
            model_name='index',
            name='mont_payer',
            field=models.BigIntegerField(default=None, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='index',
            name='niu',
            field=models.CharField(max_length=50, verbose_name='NIU'),
        ),
        migrations.AlterField(
            model_name='index',
            name='nouvel_ind',
            field=models.IntegerField(default=None, verbose_name='Nouvel index'),
        ),
        migrations.AlterField(
            model_name='index',
            name='prix_unit',
            field=models.BigIntegerField(default=None, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='index',
            name='rccm',
            field=models.CharField(max_length=50, verbose_name='RCCM'),
        ),
        migrations.AlterField(
            model_name='index',
            name='tel',
            field=models.BigIntegerField(default=None, verbose_name='Tel'),
        ),
    ]
