# Generated by Django 4.1.3 on 2024-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0046_alter_aot_duree_bail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aot',
            name='date_debut',
            field=models.DateField(default=None, verbose_name='Date facturation loyer'),
        ),
    ]
