# Generated by Django 4.2 on 2025-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0047_alter_aot_date_debut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="index",
            name="id",
        ),
        migrations.AlterField(
            model_name="index",
            name="objectid",
            field=models.IntegerField(primary_key="True", serialize=False),
        ),
    ]
